'use strict';

var configExport = {
  ENERGY_TYPES : {
    COAL : {
      name: 'Coal',
      abbr: 'Co',
      desc: 'A readily combustible black or brownish-black rock whose composition, including inherent moisture, consists of more than 50 percent by weight and more than 70 percent by volume of carbonaceous material. It is formed from plant remains that have been compacted, hardened, chemically altered, and metamorphosed by heat and pressure over geologic time.'
    },
    NATURAL_GAS: {
      name: 'Natural Gas',
      abbr: 'Na',
      desc: 'A gaseous mixture of hydrocarbon compounds, the primary one being methane.'
    },
    SOLAR: {
      name: 'Solar',
      abbr: 'So',
      desc: 'The radiant energy of the sun, which can be converted into other forms of energy, such as heat or electricity.'
    },
    WIND: {
      name: 'Wind',
      abbr: 'Wi',
      desc: 'Kinetic energy present in Wind motion that can be converted to mechanical energy for driving pumps, mills, and electric power generators.'
    },
    NUCLEAR: {
      name: 'Nuclear',
      abbr: 'Nu',
      desc: 'Electricity generated by the use of the thermal energy released from the fission of nuclear fuel in a reactor.'
    },
    MOTOR_GASOLINE: {
      name: 'Motor Gasoline',
      abbr: 'Ga',
      desc: 'A complex mixture of relatively volatile hydrocarbons with or without small quantities of additives, blended to form a fuel suitable for use in spark-ignition engines.'
    }
  }
}

exports = module.exports = configExport;
